export interface DebitNotePayloadModel {
    "invoice_id": number,
    "customer_id": number,
    "salesman_id": number,
    "debit_note_number": string,
    "debit_note_date": string,
    "payment_term_id": number,
    "items": DebitNoteItemPayloadModel[],
    "total_qty": number,
    "total_gross": number,
    "total_discount_amount": number,
    "total_net": number,
    "total_vat": number,
    "total_excise": number,
    "grand_total": number,
    "debit_note_comment": string,
    "source" : string,
};

export interface DebitNoteItemPayloadModel {
    "item_id": number,
    "item_uom_id": number,
    "discount_id": number,
    "item_condition": number,
    "is_free": boolean,
    "is_item_poi": boolean,
    "promotion_id": number | null,
    "item_qty": number,
    "item_price": number,
    "item_gross": number,
    "item_discount_amount": number,
    "item_vat": number,
    "item_net": number,
    "item_excise": number,
    "item_grand_total": number,
    "batch_number": number | null,
    "reason": string,
}